### ISSUE TITLE
component_config usage

### ISSUE THREAD

**Issue by N-Mi** [bechtoldt/saltstack-pam-formula#1]
Hi,

Thank you for this Salt Formula.

I had some troubles using it, but I don't know if it's because I misconfigured something or if something is wrong in your formula.

I've put the following configuration in the pillar file :

```
pam:
  lookup:
    pkgs:
      - libpam-modules
    component_config:
      vsftpd:
        - facility: auth
          control: required
          module: pam_userdb.so
          args:
            - db=/etc/vsftpd_login
        - facility: account
          control: required
          module: pam_userdb.so
          args:
            - db=/etc/vsftpd_login
```

And got the following error message when doing a state.highstate :

```
----------
          ID: pam_comp_config_vsftpd
    Function: file.managed
        Name: /etc/pam.d/vsftpd
      Result: False
     Comment: Source file salt://pam/files/component_config not found
     Started: 14:33:25.680577
    Duration: 5.952 ms
     Changes:   
```

I've installed the formula in `/srv/formulas/pam-formula/` (and added this directory in file_roots in master's conf).

I managed to make it work by adding a symlink from `/srv/formulas/pam-formula/pam/files` to `/srv/formulas/pam-formula/contrib/files`, but I don't think this is a "clean" solution.

Can you tell me (or document) how to use this formula the right way ?

Thanks,

N-Mi.
